### ISSUE TITLE
List strings supported in popup

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-helpscout-chrome-extension#2]
Chrome extensions give us a neat little popup easily. I'd like to make that list all the strings that are supported so you can quickly check against it. Initially it will be statically populated but at some point I'd like to make the list more dynamic.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by brashrebel** [comment]
This is done and is pretty handy. Not only can you see the supported strings/links in the popup but you can also drag them into textareas or just copy them.
<img width="315" alt="screenshot 2016-04-15 08 46 17" src="https://cloud.githubusercontent.com/assets/4993131/14561780/b7a1e4f0-02e6-11e6-972d-b082c100b1c4.png">
